### PR TITLE
Paging and scroll fixes

### LINKED ISSUE #1093: dH doesn't work like dL
dL deletes from cursor to last line of window. dH should delete from cursor to first line in window, but deletes ONLY the first line.

Love the extension BTW! Used to pay $100 for a commercial product that wasn't even as good.

### LINKED ISSUE #1888: H/L in combination with `set scrolloff=2`
When using `set scrolloff=2`, H will jump to the top of the screen instead of top+2, thus causing the window to scroll. L has the same issue.

E.g. when the top line is 20 and I press H, the top line is now 18 with the cursor placed on 20.

### PR DESCRIPTION
**Pull request by ricksladkey**
### Changes
- Prevent `<C-f>` from reaching the phantom line
- Prevent `<C-d>` from reaching the phantom line
- Prevent display of the phantom line when going to the end of the file with `G`
- Systematically use the `GetTextViewLines` API to avoid exception handling boilerplate
- Ensure screen motions (`H` and `L`) only move to fully visible lines
- Fix screen motions (`H` and `L`) combined with scrolloff
- Handle scrolling by line (`<C-e>` and `<C-y>`) when line wrapping is in effect
- Fix scrolling by line can position the cursor partially offscreen
- Increase coverage of paging and scrolling scrolling tests

### Fixes
- Fixes additional cases not mentioned in the closed issue #2113
- Fixes #1888
- Closes #1093 (already fixed)

### CODE REVIEW

File: Src/VimCore/CommandUtil.fs [hunk 1]
```diff
@@ -1779,23 +1779,20 @@ type internal CommandUtil
     /// Happens when the middle mouse button is clicked.  Need to paste the contents of the default
     /// register at the current position
     member x.PutAfterCaretMouse() =
-        try
+        match TextViewUtil.GetTextViewLines _textView with
```
Comment (jaredpar) [inline Src/VimCore/CommandUtil.fs]: Consider combining the match clauses.

File: Src/VimCore/EditorUtil.fs [hunk 2]
```diff
@@ -1818,13 +1818,19 @@ module TextViewUtil =
...
     let GetTextViewLines (textView: ITextView) =
-        try
-            let textViewLines = textView.TextViewLines
-            if textViewLines <> null then Some textViewLines
-            else None
-        with 
+        if textView.IsClosed || textView.InLayout then
+
             // TextViewLines can throw if the view is being laid out.  Highly unlikely we'd hit
             // that inside of Vim but need to be careful
```
Comment (jaredpar) [inline Src/VimCore/EditorUtil.fs]: It's actually likely during startup that we end up executing VsVim commands during a layout. Over the years I've had a number of bug reports in this area. Essentially every startup sequence for different file types is a bit of a race condition. As such the editor ends up firing off events while it's still in the middle of a layout. Once we're past startup though it's pretty unlikely.

File: Src/VimCore/CommandUtil.fs (hunk 1 above)
Comment (ricksladkey) [reply Src/VimCore/CommandUtil.fs]: Gotcha, we can match on a tuple because we need both of them to be some value.

File: Src/VimCore/EditorUtil.fs (hunk 2 above)
Comment (ricksladkey) [reply Src/VimCore/EditorUtil.fs]: Unfortunately I can think of no easy way to force F# clients to use our bulletproof API. At least when trying to do something in VsVim, people like me who search around for something similar to build off of will now only find uses of the preferred API.
