### PR TITLE
Use the last line when clicking below the end of the buffer

### LINKED ISSUE #2586: Clicking past end of file doesn't move cursor to end of file anymore
**Describe the bug**
When scrolling past the end of a file, clicking in the empty space underneath the source code doesn't move the cursor to the last line.

**To Reproduce**

1.  Go to any file
2.  Click in the empty area underneath the last line of code

**Expected behavior**
The cursor should move to the end of the file.

**Screenshots**
image
Clicking in the space underneath line 18 used to move the cursor to last line of code. Instead, the cursor stays where it's at (line 14 in this pic)

**Environment (please complete the following information):**

- Visual Studio version: 15.9.12
- VsVim version: 2.7.0.0
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

**Additional context**
This didn't happen with 2.6.0.0 and when disabling VsVim it works as expected.

### PR DESCRIPTION
**Pull request by ricksladkey**
#### Issues

- Closes #2586

### CODE REVIEW

File: Src/VimCore/CommonOperations.fs [hunk 1]
```diff
@@ -94,6 +94,22 @@ type internal CommonOperations
...
+                    let lastLineNumber =
+                        TextViewUtil.GetSnapshot _textView
+                        |> SnapshotUtil.GetLastLineNumber
+                    let lastVisibleLine = textViewLines.LastVisibleLine
+                    let lastVisibleLineNumber =
+                        lastVisibleLine.Start.GetContainingLine().LineNumber
+                    if lastVisibleLineNumber = lastLineNumber then
+                        lastVisibleLine
+                    else
+                        textViewLine
```
Comment (jaredpar) [inline Src/VimCore/CommonOperations.fs]: Consider using literal `null` here to make it apparent that's what is happening

Comment (ricksladkey) [reply Src/VimCore/CommonOperations.fs]: That is clearer. Done.
