### PR TITLE
Handle '<C-LeftRelease>' in normal mode

### LINKED ISSUE #2580: Selection not cleared after control-click to go to definition
**Describe the bug**

When using `<C-LeftMouse>` to "go to definition" and the definition is in the same file, the selection is not cleared.

**To Reproduce**

1. In a C# buffer with the following contents:

```
namespace Vim
{
    internal sealed class Test1
    {
        private readonly int _test2;
        public int Test2 => _test2;
    }
}
```

2. Use `<C-LeftMouse>` to "go to definition" on the second occurrence of `_test2`.
3. The first occurrence of `_test2` will be selected and the buffer will be in visual or select character mode.

**Expected behavior**

The caret is resting on the `_` of `_test2` in normal mode.

**Environment (please complete the following information):**

- Visual Studio version: 2019
- VsVim version: 2.7.0
- Programming Language: C#
- Check(Type 'x') any that are installed:
    - [ ] ReSharper
    - [ ] Visual Assist

### PR DESCRIPTION
**Pull request by ricksladkey**
#### Issues

- Closes #2580

### CODE REVIEW

File: Test/VimCoreTest/NormalModeTest.cs [hunk 1]
```diff
@@ -183,6 +183,18 @@ public void CanProcess_PrintableNonAscii()
             Assert.False(_mode.CanProcess(KeyInputUtil.CharToKeyInput('´')));
         }
 
+        /// <summary>
+        /// Verify that normal mode can process both C-LeftMouse and C-LeftRelease
+        /// </summary>
+        [WpfFact]
+        public void CanProcess_ControlClickAndRelease()
```
Comment (jaredpar) [inline Test/VimCoreTest/NormalModeTest.cs]: Consider adding a test that verifies this action doesn't impact repeat last command (the `.` operator).

Comment (ricksladkey) [reply Test/VimCoreTest/NormalModeTest.cs]: Good idea!  Added one.
